version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    build: .
    image: post-admission-api
    environment:
      PORT: 8080
      NODE_ENV: production
      DB_URL: postgresql://postgres:password@db:5432/post_admission_db
    ports:
      - "8080:8080"
    depends_on:
      - db
