openapi: 3.0.1
info:
  title: Post Admission
  description: This is the service that is used post admission.
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /students/{studentId}:
    post:
      tags:
      - Student
      summary: New student form submission
      operationId: postStudentForm
      parameters: 
        - name: studentId
          in: path
          required: true
          description: Id of the student who is supposed to fill the post admission form
          schema:
            type : string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
        
      responses:
        201:
          description: Created
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  data: 
                    type: object
                    properties:
                      id: 
                        type: string
              
        400:
          description: Bad Request
          content:
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: array
                    items: 
                      type: object
                      properties:
                        msg: 
                          type: string
                        param:
                          type: string
                        location:
                          type: string
        500:
          description: Internal server error
          content:  
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: string
  /students/{id}:
    get:
      tags:
      - Student
      summary: Find student details by ID
      description: Returns a single student
      operationId: getStudentById
      parameters:
      - name: id
        in: path
        description: ID of student whose details to return
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Student'
        500:
          description: Internal server error
          content:  
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: string
                    
  /students/all:
    get:
      tags:
      - Student
      summary: Find student details by ID
      description: Returns a single student
      operationId: getAllStudents
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Student'
        500:
          description: Internal server error
          content:  
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: string
components:
  schemas:
    Student:
      required:
      - annual_family_income
      - blood_group
      - email
      - marital_status
      - nationality
      - area
      - _state
      - father_name
      - mother_name
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Id of this form
        studentId:
          type: string
          description: Id of the student whose details these are
        nri:
          type: boolean
        email:
          type: string
        religion:
          type: string
        nationality:
          type: string
        blood_group:
          type: string
        marital_status:
          type: string
          enum:
          - single
          - widow
          - married
        annual_family_income:
          type: string
        area:
          type: string
          enum:
          - urban
          - rural
        _state:
          type: string
        current_address:
          type: string
        permanent_address:
          type: string
        father_name:
          type: string
        father_email:
          type: string
        father_phone:
          type: string
        father_occupation:
          type: string
        mother_name:
          type: string
        mother_email:
          type: string
        mother_phone:
          type: string
        mother_occupation:
          type: string
        bpl:
          type: string
          format: binary
        img:
          type: string
          format: binary
        pwd:
          type: string
          format: binary
        twitter:
          type: string
        facebook:
          type: string
        instagram:
          type: string
      xml:
        name: Student
