openapi: 3.0.1
info:
  title: Post Admission
  description: This is the service that is used post admission.
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /api/uploads/selfie:
    post:
      tags:
        - Student
      summary: Post a selfie  
      operationId: postSelfie
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Image:
                  type: string
                  format: binary
              required: 
                - Image
      responses:
        200:
          description: Uploaded
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  size: 
                    type: number
                  filePath:
                    type: string
                  fileName:
                    type: string
        500:
          description: Internal server error
          content:  
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: string
          
  /api/uploads/bpl:
    post:
      tags:
        - Student
      summary: Post bpl certificate  
      operationId: postBpl
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Bpl Certificate:
                  type: string
                  format: binary
              required: 
                - Bpl Certificate
      responses:
        200:
          description: Uploaded
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  size: 
                    type: number
                  filePath:
                    type: string
                  fileName:
                    type: string
        500:
          description: Internal server error
          content:  
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: string    
                    
  /api/uploads/pwd:
    post:
      tags:
        - Student
      summary: Post pwd certificate  
      operationId: postPwd
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Pwd Certificate:
                  type: string
                  format: binary
              required: 
                - Pwd Certificate
      responses:
        200:
          description: Uploaded
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  size: 
                    type: number
                  filePath:
                    type: string
                  fileName:
                    type: string
        500:
          description: Internal server error
          content:  
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: string                    
  /api/{studentId}:
    post:
      tags:
      - Student
      summary: New student form submission
      operationId: postStudentForm
      parameters: 
        - name: studentId
          in: path
          required: true
          description: Id of the student who is supposed to fill the post admission form
          schema:
            type : string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
        
      responses:
        201:
          description: Created
              
        400:
          description: Bad Request
          content:
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: array
                    items: 
                      type: object
                      properties:
                        msg: 
                          type: string
                        param:
                          type: string
                        location:
                          type: string
        500:
          description: Internal server error
          content:  
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: string
  /api/{id}:
    get:
      tags:
      - Student
      summary: Find student details by ID
      description: Returns a single student
      operationId: getStudentById
      parameters:
      - name: id
        in: path
        description: ID of student whose details to return
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Student'
        500:
          description: Internal server error
          content:  
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: string
                    
  /api/all:
    get:
      tags:
      - Student
      summary: Get all students submissions
      operationId: getAllStudents
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Student'
        500:
          description: Internal server error
          content:  
            application/json:
              schema: 
                type: object
                properties:
                  error: 
                    type: string
components:
  schemas:
    Student:
      required:
      - studentId
      - name
      
      - blood_group
      - religion
      - marital_status
      - annual_family_income
      - area
      - nationality
      
      - current_address_line_1
      - current_city
      - current_state
      - current_zip_code
      - current_country
      
      - permanent_address_line_1
      - permanent_city
      - permanent_state
      - permanent_zip_code
      - permanent_country
      
      - father_name
      - father_phone
      - father_occupation
      
      - mother_name
      - mother_phone
      - mother_occupation
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Id of this form
        studentId:
          type: string
          description: Id of the student whose details these are
        nri:
          type: boolean
        name:
          type: string
        religion:
          type: string
        nationality:
          type: string
        blood_group:
          type: string
        marital_status:
          type: string
          enum:
          - Single
          - Widow
          - Married
        annual_family_income:
          type: string
        area:
          type: string
          enum:
          - Urban
          - Rural
          
        current_address_line_1: 
          type: string
        current_address_line_2:
          type: string
        current_city: 
          type: string
        current_state: 
          type: string
        current_zip_code: 
          type: string
        current_country: 
          type: string
          
        permanent_address_line_1: 
          type: string
        permanent_address_line_2:
          type: string
        permanent_city:
          type: string
        permanent_state:
          type: string
        permanent_zip_code: 
          type: string
        permanent_country: 
          type: string
      
          
        father_name:
          type: string
        father_email:
          type: string
        father_phone:
          type: string
        father_occupation:
          type: string
        
        mother_name:
          type: string
        mother_email:
          type: string
        mother_phone:
          type: string
        mother_occupation:
          type: string
        
        bpl:
          type: string
        img:
          type: string
        pwd:
          type: string
        
        twitter:
          type: string
        facebook:
          type: string
        instagram:
          type: string
      xml:
        name: Student
